from typing import List
from app.models.models import Paystub, BenefitSummary

def llm_extract_benefits_from_paystub(paystub: Paystub) -> dict:
    """
    TODO: call OpenAI GPT-4.1-mini with a structured extraction prompt.
    For now, derive from parsed_data stub.
    """
    data = paystub.parsed_data or {}
    return {
        "hsa_balance": data.get("hsa_balance", 0),
        "hsa_contribution_ytd": 0,
        "fsa_balance": data.get("fsa_balance", 0),
        "fsa_deadline": None,
        "pto_balance_hours": data.get("pto_hours", 0),
        "pto_accrual_hours_per_period": 4,
        "k401_contribution_percent": 5,
        "k401_employer_match_percent": 4,
        "deductible_total": 2000,
        "deductible_used": 500,
        "raw_summary": {
            "explanation": "Stubbed benefits summary generated by LLM.",
            "source": "stub",
        },
    }


def llm_generate_recommendations(summary: BenefitSummary) -> List[dict]:
    """
    TODO: call LLM to generate recommendations based on summary.
    """
    recs = []

    if summary.k401_contribution_percent and summary.k401_employer_match_percent:
        if float(summary.k401_contribution_percent) < float(
            summary.k401_employer_match_percent
        ):
            recs.append(
                {
                    "title": "Increase 401(k) contribution",
                    "description": "You are below your employer match rate. Consider increasing to at least the match to avoid leaving money on the table.",
                    "estimated_savings": 500,
                    "category": "401k",
                    "priority": "high",
                }
            )

    if summary.fsa_balance and summary.fsa_balance > 0:
        recs.append(
            {
                "title": "Use your FSA balance",
                "description": "You have unused FSA balance. Schedule eligible health expenses before it expires.",
                "estimated_savings": float(summary.fsa_balance),
                "category": "FSA",
                "priority": "medium",
            }
        )

    if summary.pto_balance_hours and summary.pto_balance_hours > 80:
        recs.append(
            {
                "title": "Take some PTO",
                "description": "Your PTO balance is high. Consider taking time off to avoid hitting accrual caps.",
                "estimated_savings": None,
                "category": "PTO",
                "priority": "medium",
            }
        )

    if not recs:
        recs.append(
            {
                "title": "Your benefits look on track",
                "description": "We didn’t find any urgent actions. Review your benefits annually or when your life situation changes.",
                "estimated_savings": None,
                "category": "general",
                "priority": "low",
            }
        )

    return recs
