id: benefits-trend-analysis
namespace: clearperks.analytics

description: Weekly aggregation of benefits usage trends across all users

variables:
  api_url: "https://iampratham29-clear-perks-backend.hf.space"
  api_key: "changeme"

tasks:
  - id: aggregate-benefits-data
    type: io.kestra.plugin.core.http.Request
    uri: "{{ vars.api_url }}/api/v1/kestra/aggregate"
    method: POST
    headers:
      X-Internal-Key: "{{ vars.api_key }}"
      Content-Type: application/json
    body: |
      {
        "period": "weekly",
        "metrics": ["hsa_usage", "fsa_usage", "pto_balance", "401k_contribution"]
      }
    
  - id: generate-insights
    type: io.kestra.plugin.core.http.Request
    uri: "{{ vars.api_url }}/api/v1/kestra/insights"
    method: POST
    headers:
      X-Internal-Key: "{{ vars.api_key }}"
      Content-Type: application/json
    body: |
      {
        "aggregation_id": "{{ outputs['aggregate-benefits-data'].body.id }}",
        "generate_recommendations": true
      }
    
  - id: notify-admins
    type: io.kestra.plugin.core.http.Request
    uri: "{{ vars.api_url }}/api/v1/admin/notifications"
    method: POST
    headers:
      X-Internal-Key: "{{ vars.api_key }}"
      Content-Type: application/json
    body: |
      {
        "title": "Weekly Trends Report Ready",
        "message": "New benefits usage insights are available for review.",
        "report_id": "{{ outputs['generate-insights'].body.report_id }}"
      }

triggers:
  - id: weekly-analysis
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 8 * * 1"
