id: fsa-deadline-alert
namespace: clearperks.benefits

description: Monthly check for FSA deadlines and send notifications to users

variables:
  api_url: "https://iampratham29-clear-perks-backend.hf.space"
  api_key: "changeme"

tasks:
  - id: check-fsa-deadlines
    type: io.kestra.plugin.core.http.Request
    uri: "{{ vars.api_url }}/api/v1/kestra/fsa-audit"
    method: GET
    headers:
      X-Internal-Key: "{{ vars.api_key }}"
    
  - id: parse-users
    type: io.kestra.plugin.core.flow.EachSequential
    value: "{{ outputs['check-fsa-deadlines'].body | jq('.users_at_risk') }}"
    tasks:
      - id: send-notification
        type: io.kestra.plugin.core.http.Request
        uri: "{{ vars.api_url }}/api/v1/users/{{ taskrun.value.user_id }}/notifications"
        method: POST
        headers:
          X-Internal-Key: "{{ vars.api_key }}"
          Content-Type: application/json
        body: |
          {
            "title": "FSA Deadline Approaching",
            "message": "You have ${{ taskrun.value.fsa_balance }} in your FSA that expires soon. Use it or lose it!",
            "category": "FSA",
            "priority": "high"
          }

triggers:
  - id: monthly-schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 1 * *"
