id: ocr-batch-reprocess
namespace: clearperks.maintenance

description: Batch reprocess failed or pending OCR jobs

variables:
  api_url: "https://iampratham29-clear-perks-backend.hf.space"
  api_key: "changeme"

tasks:
  - id: fetch-failed-paystubs
    type: io.kestra.plugin.core.http.Request
    uri: "{{ vars.api_url }}/api/v1/paystubs?status=error&status=processing"
    method: GET
    headers:
      X-Internal-Key: "{{ vars.api_key }}"
    
  - id: reprocess-each
    type: io.kestra.plugin.core.flow.EachSequential
    value: "{{ outputs['fetch-failed-paystubs'].body | jq('.paystubs') }}"
    tasks:
      - id: trigger-reprocess
        type: io.kestra.plugin.core.http.Request
        uri: "{{ vars.api_url }}/api/v1/paystubs/{{ taskrun.value.id }}/reprocess"
        method: POST
        headers:
          X-Internal-Key: "{{ vars.api_key }}"
          
      - id: wait-for-completion
        type: io.kestra.plugin.core.flow.Sleep
        duration: PT30S

triggers:
  - id: weekly-cleanup
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 2 * * 0"
